# ====================================================================================================
# P05b_gui_elements_main.py
# ----------------------------------------------------------------------------------------------------
# Provides the locked, universal base GUI class used across all projects.
# This file defines the shared window structure, lifecycle behaviour, and styling.
# Do not modify — project GUIs extend this via subclassing.
# ----------------------------------------------------------------------------------------------------
# Author:       Gerry Pidgeon
# Created:      2025-11-07
# Project:      GP Boilerplate
# ====================================================================================================

# ====================================================================================================
# 1. SYSTEM IMPORTS
# ----------------------------------------------------------------------------------------------------
# Add parent directory to sys.path so this module can import other "processes" packages.
# ====================================================================================================
import sys
from pathlib import Path

# --- Standard block for all modules ---
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.dont_write_bytecode = True  # Prevents __pycache__ folders from being created

# ====================================================================================================
# 2. PROJECT IMPORTS
# ----------------------------------------------------------------------------------------------------
# Bring in standard libraries and settings from the central import hub.
# ====================================================================================================
from processes.P00_set_packages import *

# ====================================================================================================
# 3. MAIN BASE GUI CLASS (LOCKED)
# ----------------------------------------------------------------------------------------------------
# Purpose:
#   Defines the generic top-level window used by all projects after successful setup.
#   This class provides:
#       - A consistent look and layout across all projects.
#       - Common lifecycle behaviour (window creation, close handling).
#       - Shared styling and footer components.
#       - An overridable `build_gui()` method that project GUIs can extend.
#
# Notes:
#   Do not edit this file for project-specific changes.
#   Instead, create a subclass in `/implementation/` that overrides `build_gui()`.
# ====================================================================================================

class BaseMainGUI(tk.Toplevel):
    """
    Initialize the locked base GUI.

    Args:
        parent (tk.Widget): The parent window or Tk root.
        snowflake_conn: Optional live Snowflake connection object.
        gdrive_service: Optional Google Drive API service object.
        upload_method (str): 'api' or 'local'.
        local_path (str): Selected local folder path.
        title (str): Window title.
    """

    def __init__(self, parent, snowflake_conn=None, gdrive_service=None,
                 upload_method=None, local_path=None, title="Main Application"):
        super().__init__(parent)
        self.title(title)
        self.geometry("800x600")
        self.configure(bg="#f7f7f7")

        # --- Store connection references ---
        self.parent = parent
        self.snowflake_conn = snowflake_conn
        self.gdrive_service = gdrive_service
        self.upload_method = upload_method
        self.local_path = local_path

        # --- Shared styles ---
        style = ttk.Style(self)
        style.configure("TFrame", background="#f7f7f7")
        style.configure("TLabel", background="#f7f7f7")
        style.configure("Accent.TButton", font=("Arial", 10, "bold"))

        # --- Main container for project GUI content ---
        self.main_frame = ttk.Frame(self, padding=20)
        self.main_frame.pack(expand=True, fill="both")

        # --- Shared footer (locked) ---
        ttk.Separator(self).pack(fill="x", pady=5)
        footer = ttk.Frame(self, padding=10)
        footer.pack(fill="x")
        ttk.Button(footer, text="Close Application", command=self.quit,
                   style="Accent.TButton").pack(side="right")

        # --- Call the extension hook (implemented by project subclass) ---
        self.build_gui()

    # ================================================================================================
    # EXTENSION POINT
    # ================================================================================================
    def build_gui(self):
        """
        Override this method in the project-specific GUI subclass
        (e.g. I02_gui_elements_main.py) to build the interface.
        """
        ttk.Label(
            self.main_frame,
            text="🚧 No project GUI provided.\nOverride build_gui() in your subclass.",
            font=("Arial", 12, "italic"),
            foreground="red"
        ).pack(expand=True)

# ====================================================================================================
# END OF FILE — DO NOT MODIFY (LOCKED)
# ====================================================================================================